spring:
# MySQL properties
    datasource:
        url: jdbc:mysql://localhost:3306/vttpfinalproject
        username: vttpfinalproject
        password: vttpfinalproject
# MongoDB properties
    data:
      mongodb:
        host: localhost
        port: 27017
        # username:
        # password:
        database: vttpfinalproject
        authentication-database: admin
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
